version: "3.8"

services:
  app:
    container_name: django-nginx
    build:
      context: .
    volumes:
       - .:/usr/src/app/
    depends_on:
        - pgdb
  #   volumes:
  #     - static_data:/vol/web
    # environment:
    #   - SECRET_KEY=samplesecret123
    #   - ALLOWED_HOSTS=127.0.0.1,localhost
  pgdb:
    image: postgres:10
    container_name: pgdb
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres   
    volumes:
        # - pgdata:/var/lib/postgresql/data/
        - pgdata:/usr/src/app/
    ports:
        - "5432:5432" 
  proxy:
    build:
      context: ./proxy
    volumes:
      # - static_data:/vol/static
      - .:/usr/src/app/
    ports:
      - "9080:9080"
    depends_on:
      - app
      - pgdb
  
  redis:
    container_name: redis
    image: "redis:alpine"
    environment:
      TZ: Europe/Warsaw
  
  celery:
    container_name: celery
    build: .
    command: celery -A trainersdjango worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
      - app
      - pgdb
  flower:
    container_name: flower
    build: .
    command: celery -A trainersdjango flower --port=5555
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on: 
      - celery
      - app
      - redis
      - pgdb 

volumes:
  static_data:
  pgdata: