# Generated by Django 3.2 on 2021-08-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0002_auto_20210804_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
