# Generated by Django 3.2 on 2021-07-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0002_event_package_trainerhoursperday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'package', 'verbose_name_plural': 'packages'},
        ),
        migrations.AlterModelOptions(
            name='trainerhoursperday',
            options={'ordering': ('weekday', 'from_hour'), 'verbose_name': 'hour', 'verbose_name_plural': 'hours'},
        ),
        migrations.AddField(
            model_name='event',
            name='client_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='client_phone',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerspro.package'),
        ),
    ]
