# Generated by Django 3.2 on 2021-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0003_rename_plans_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='package_num',
            field=models.IntegerField(default=1),
        ),
    ]
