# Generated by Django 3.2 on 2021-08-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0004_event_package_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='package_num',
        ),
        migrations.AddField(
            model_name='plan',
            name='package_num',
            field=models.IntegerField(default=1),
        ),
    ]
