# Generated by Django 3.2 on 2021-08-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0006_auto_20210806_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='events',
            field=models.ManyToManyField(blank=True, to='trainerspro.Event'),
        ),
    ]
