# Generated by Django 3.2 on 2021-08-09 10:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0007_alter_plan_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+48501779384', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+48501779384', max_length=128, region=None),
        ),
    ]
