# Generated by Django 3.2 on 2021-08-21 12:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0008_auto_20210809_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trainer_picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
