# Generated by Django 3.2 on 2021-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0009_auto_20210821_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
