# Generated by Django 3.2 on 2021-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerspro', '0011_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='end_number_of_kg',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformation',
            name='start_number_of_kg',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
